Adding CBZ export option with embedded ComicInfo.xml
Zeal-L/BiliBili-Manga-Downloader pull request #98
Opened 2023-11-27 01:34 UTC by averageFOSSenjoyer

### Background
- `ComicInfo.xml` is a metadata evaluation file used by various comics media server like komga and kavita. 
  - https://github.com/anansi-project/comicinfo
- `cbz` is effectively `zip` but far more recognizable by media servers along with the ability to embed metadata like the `ComicInfo.xml` mentioned above
  - Some media server may not recognize the metadata if the format is not in `cbz`

### Changes
Created `ComicInfoXML` class as metadata container and serializer
Added option to export comics as CBZ in UI and backend

### Preview
![2023-11-26_19-30](https://github.com/Zeal-L/BiliBili-Manga-Downloader/assets/70647872/aa597d37-d30f-47fa-be86-bf1468c04129)
![2023-11-26_19-33](https://github.com/Zeal-L/BiliBili-Manga-Downloader/assets/70647872/548c4042-82c2-41a1-960b-7fb6733b5472)

2023-11-27 04:54 UTC, shadlc requested changes
I think there is room for improvement.

2023-11-27 04:54 UTC, shadlc commented on src/ComicInfoXML.py
> +        with open(os.path.join(output_path, 'ComicInfo.xml'), 'w', encoding="utf-8") as f:
Will there be an exception occurred when mutiple download is processing, cause there just single comic info file for all tasks?

2023-11-27 04:54 UTC, shadlc commented on src/ComicInfoXML.py
> +class ComicInfoXML:
This class is no unified commit style

2023-11-27 06:46 UTC, averageFOSSenjoyer commented on src/ComicInfoXML.py
> +        with open(os.path.join(output_path, 'ComicInfo.xml'), 'w', encoding="utf-8") as f:
i don't believe so
as far as i can tell, each download is associated with an `Episode` object, which in turns carries a `ComicInfoXML` object
the `output_path` given is post aggregation of the images into the episode folder and precompression, so there wouldnt be a conflict
i have tested this myself with 16 download threads

2023-11-27 06:46 UTC, averageFOSSenjoyer commented on src/ComicInfoXML.py
> +class ComicInfoXML:
not sure what you meant by unified commit style, do you need the helper as a method of the class?

2023-11-27 06:50 UTC, averageFOSSenjoyer commented on src/Episode.py
> +        if mainGUI.getConfig("save_method") == "Cbz压缩包":
tbh I am not completely sure on how the prorgam handles settings
i noticed that maingui is reference in both constructor and the save function, wouldnt be better to save the save_method when the download is called aka when the `Episode` object is constructed, instead of having to rely on real time look up during the save

2023-11-27 08:16 UTC, shadlc commented on src/ComicInfoXML.py
> +class ComicInfoXML:
Yes, but it's okay. It would be better if you could make some changes.

2023-11-27 08:21 UTC, shadlc commented on src/ComicInfoXML.py
> +        with open(os.path.join(output_path, 'ComicInfo.xml'), 'w', encoding="utf-8") as f:
That will be fine

2023-11-27 16:52 UTC, Zeal-L commented on src/Episode.py
> +        if mainGUI.getConfig("save_method") == "Cbz压缩包":
You're right, I just re-read the logic and it's actually a historical issue, in the beginning this save_method would only be loaded once when the program was started and there was no way for the user to switch the save method on the fly. At that time, for convenience, the configuration was read directly in save(). This doesn't actually cause any errors until you add this new save method this time. I've pushed the fix code in devlop's latest commit, please pull it.

Translated with www.DeepL.com/Translator (free version)

2023-11-27 16:55 UTC, Zeal-L commented on src/ComicInfoXML.py
> +class ComicInfoXML:
What @shadlc  really means is that he wants you to add the appropriate docstring to the ComicInfoXML class based on the code's existing comment norms.

2023-11-27 17:04 UTC, Zeal-L requested changes

2023-11-27 17:04 UTC, Zeal-L commented on src/ComicInfoXML.py
> +from iso8601 import parse_date
Its better not to introduce non-essential dependencies, which can cause the program to be packaged larger, use datetime.strptime to parse ISO 8601 dates by specifying the appropriate format string.

2023-11-28 04:47 UTC, shadlc approved these changes
LGTM

2023-11-28 04:50 UTC, Zeal-L commented
@averageFOSSenjoyer  尊敬的舰长大人，Thank you very much for your contribution~ We've officially adopted the new features you've written!

![20231128-124838](https://github.com/Zeal-L/BiliBili-Manga-Downloader/assets/72005386/9f7e25f4-02f2-41df-8c3f-40046de1d4ff)

2023-11-28 04:50 UTC, merged